version : '3'
services :
  db:
    build: ./mariadb
    restart: always
    volumes:
      - ./sharevolume/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
  server :
    build: .
    volumes :
      - /docker-api/node_modules
      - ./:/docker-api
    ports:
      - "8080:4000"
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8000:80
    links:
      - db    